export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SMSF_MEMBER_LOAD = 'SMSF_MEMBER_LOAD';
export const SMSF_MEMBER_SEARCH = 'SMSF_MEMBER_SEARCH';
export const SMSF_MEMBER_CREATE = 'SMSF_MEMBER_CREATE';
export const SMSF_MEMBER_UPDATE = 'SMSF_MEMBER_UPDATE';
export const SMSF_MEMBER_DELETE = 'SMSF_MEMBER_DELETE';
export const SELECT_SMSF_MEMBER = 'SELECT_SMSF_MEMBER';