export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SIGNUP_BI_START = 'SIGNUP_BI_START';
export const SIGNUP_BI_SUCCESS = 'SIGNUP_BI_SUCCESS';
export const SIGNUP_BI_FAIL = 'SIGNUP_BI_FAIL';

export const SIGNUP_PI_START = 'SIGNUP_PI_START';
export const SIGNUP_PI_SUCCESS = 'SIGNUP_PI_SUCCESS';
export const SIGNUP_PI_FAIL = 'SIGNUP_PI_FAIL';

export const SIGNUP_FI_START = 'SIGNUP_FI_START';
export const SIGNUP_FI_SUCCESS = 'SIGNUP_FI_SUCCESS';
export const SIGNUP_FI_FAIL = 'SIGNUP_FI_FAIL';

export const SIGNUP_AF_START = 'SIGNUP_AF_START';
export const SIGNUP_AF_SUCCESS = 'SIGNUP_AF_SUCCESS';
export const SIGNUP_AF_FAIL = 'SIGNUP_AF_FAIL';

export const FETCH_SMSF_MEMBER_START = 'FETCH_SMSF_MEMBER_START';
export const FETCH_SMSF_MEMBER_SUCCESS = 'FETCH_SMSF_MEMBER_SUCCESS';
export const FETCH_SMSF_MEMBER_FAIL = 'FETCH_SMSF_MEMBER_FAIL';

export const SEARCH_SMSF_MEMBER_START = 'SEARCH_SMSF_MEMBER_START';
export const SEARCH_SMSF_MEMBER_SUCCESS = 'SEARCH_SMSF_MEMBER_SUCCESS';
export const SEARCH_SMSF_MEMBER_FAIL = 'SEARCH_SMSF_MEMBER_FAIL';

export const SELECT_SMSF_MEMBER_START = 'SELECT_SMSF_MEMBER_START_START';
export const SELECT_SMSF_MEMBER_SUCCESS = 'SELECT_SMSF_MEMBER_SUCCESS';
export const SELECT_SMSF_MEMBER_FAIL = 'SELECT_SMSF_MEMBER_FAIL';

export const SAVE_SMSF_MEMBER_START = 'SAVE_SMSF_MEMBER_START';
export const SAVE_SMSF_MEMBER_SUCCESS = 'SAVE_SMSF_MEMBER_SUCCESS';
export const SAVE_SMSF_MEMBER_FAIL = 'SAVE_SMSF_MEMBER_FAIL';


